FROM node:12 as build
WORKDIR /build
COPY package*.json ./
RUN npm install

FROM node:12-alpine
WORKDIR /opt/app
RUN npm i -g nodemon
COPY nodemon.json tsconfig.json ./
COPY --from=build ./build ./
COPY ./docs ./docs
RUN npm install --only=production
EXPOSE 3001 5858 9229
