defaults: &defaults
  working_directory: ~/CLARK-Gateway
  docker:
    - image: docker:17.05.0-ce-git
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: | 
            docker build -t clark-gateway:$CIRCLE_SHA1 .
            mkdir -p docker-image
            docker save -o "docker-image/clark-gateway:${CIRCLE_SHA1}.tar" clark-gateway:$CIRCLE_SHA1
      - persist_to_workspace: 
          root: ./
          paths: 
              - ./docker-image
              - ./package.json

  unit-test:
    <<: *defaults
    steps:
      - attach_workspace : 
          at: ~/CLARK-Gateway
      - setup_remote_docker
      - run:
          name: Unit Test Image
          command: |
            docker load < "docker-image/clark-gateway:${CIRCLE_SHA1}.tar"
            echo docker run-it -d clark-gateway:$CIRCLE_SHA1 npm test
      - run:
          name: Login to docker
          command: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run:
          name: Publish Image 
          command: |
            docker tag clark-gateway:$CIRCLE_SHA1 "${DOCKER_USER_ORG}/clark-gateway:${CIRCLE_SHA1}"
            docker push "${DOCKER_USER_ORG}/clark-gateway:${CIRCLE_SHA1}"

  integration-test:
    <<: *defaults
    steps:
      - attach_workspace : 
          at: ~/CLARK-Gateway
      - setup_remote_docker
      - run:
          name: Pull Image
          command: docker pull "${DOCKER_USER_ORG}/clark-gateway:${CIRCLE_SHA1}"
      - run:
          name: Run Integration Test
          command: |
            echo docker run-it -d clark-gateway:$CIRCLE_SHA1 npm test
      - run:
          name: Print Images
          command: docker images
      - run:
          name: Login to docker
          command: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run:
          name: Publish Image 
          command: |
            export SEMVER=$(cat ./package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
            docker tag "${DOCKER_USER_ORG}/clark-gateway:${CIRCLE_SHA1}" "${DOCKER_USER_ORG}/clark-gateway:${SEMVER}"
            docker push "${DOCKER_USER_ORG}/clark-gateway:${SEMVER}"
          

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - integration-test:
          requires:
            - unit-test

  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /master/
      - unit-test:
          requires:
            - build
          filters:
            branches:
              only: /master/
      - integration-test:
          requires:
            - unit-test
          filters:
            branches:
              only: /master/
      - deploy:
          requires:
            - integration-test
          filters:
            branches:
              only: /master/