version: 2.1

orbs:
  cyber4all: cyber4all/orb@1
  docker: circleci/docker@2.0.3

workflows:
  integration-testing:
    jobs:
      - docker/hadolint:
          dockerfiles: "Dockerfile:Dockerfile.dev"
          executor-class: medium

      - cyber4all/build-app

  deploy-production:
    jobs:
      - cyber4all/sbom:
          context: [Shortcut]
          language: node
          filters:
            branches:
              only:
                - releases

      - cyber4all/build-app:
          filters:
            branches:
              only: releases


      - cyber4all/deploy-eb:
          context:
            [AWS, Slack]
          application-name: CLARK-Gateway
          environment-name: clark-gateway-production
          version: $(cat ./package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
          isDocker: false # deploy to eb as a docker image
          filters:
            branches:
              only: releases
