defaults: &defaults
  working_directory: ~/clark-gateway
  docker:
    - image: cyber4all/circleci-aws:node-alpine
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.4.0
  aws-cli: circleci/aws-cli@2.0.6
commands:
  install-aws: aws-cli/install
  setup-aws-cli: aws-cli/setup
  install-docker: docker/install-docker
version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Install OpenSSH 8.1p1
          command: |
            sudo apt-get update
            mkdir ~/tempdownload; 
            cd ~/tempdownload; 
            wget https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-8.1p1.tar.gz; 
            tar zxvf openssh-8.1p1.tar.gz; 
            cd openssh-8.1p1 && ./configure && make && sudo make install
      - checkout
      - install-docker
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Build Image
          command: | 
            docker build -t clark-gateway:$CIRCLE_SHA1 -f Dockerfile.prod .
      - run: 
          name: Login to docker
          command: docker login -u ${DOCKER_USERNAME} -p "${DOCKER_PASSWORD}"
      - run: 
          name: Publish Image
          command: | 
            docker build -t "${DOCKER_USER_ORG}/clark-gateway:${CIRCLE_SHA1}" -f Dockerfile.prod .
            docker push "${DOCKER_USER_ORG}/clark-gateway:${CIRCLE_SHA1}"
  deploy-production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/clark-gateway
      - run:
        name: Install OpenSSH 8.1p1
        command: |
          sudo apt-get update
          mkdir ~/tempdownload; 
          cd ~/tempdownload; 
          wget https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-8.1p1.tar.gz; 
          tar zxvf openssh-8.1p1.tar.gz; 
          cd openssh-8.1p1 && ./configure && make && sudo make install
      - checkout
      - install-docker
      - setup_remote_docker
      - setup-aws-cli:
          aws-access-key-id: MACHINE_AWS_EB_AccessKey
          aws-region: AWS_REGION_N_VA
          aws-secret-access-key: MACHINE_AWS_EB_SecretKey
      - run: 
          name: Login to docker
          command: docker login -u ${DOCKER_USERNAME} -p "${DOCKER_PASSWORD}"
      - run: 
          name: Pull image
          command: docker pull "${DOCKER_USER_ORG}/clark-gateway:${CIRCLE_SHA1}"
      - run: 
          name: Publish image
          command: |
            export SEMVER=$(cat ./package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
            docker tag "${DOCKER_USER_ORG}/clark-gateway:${CIRCLE_SHA1}" "${DOCKER_USER_ORG}/clark-gateway:${SEMVER}"
            docker tag "${DOCKER_USER_ORG}/clark-gateway:${CIRCLE_SHA1}" "${DOCKER_USER_ORG}/clark-gateway:latest"
            docker push "${DOCKER_USER_ORG}/clark-gateway:${SEMVER}"
            docker push "${DOCKER_USER_ORG}/clark-gateway:latest"
      - run: 
          name: Install and init eb cli
          command: | 
            pip install awsebcli
            eb init --region us-east-1 CLARK-Gateway -p docker
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            eb deploy clark-gateway-production --verbose --label clark-gateway-v$(node -p "require('./package.json').version")
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          context:
            - DockerHub
          filters:
            branches:
              ignore: /master/
  deploy:
    jobs:
      - build:
          context:
            - DockerHub
          filters:
            branches:
              only: /master/
      - deploy-production:
          requires:
            - build
          context:
            - DockerHub
            - AWS
          filters:
            branches:
              only: /master/
