defaults: &defaults
  working_directory: ~/CLARK-Gateway
  docker:
    - image: docker:17.05.0-ce-git
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: | 
            docker build -t clark-gateway:$CIRCLE_SHA1 .
            mkdir -p docker-cache
            docker save -o docker-cache/built-image.tar clark-gateway:$CIRCLE_SHA1
      - save_cache:
          key: "clark-gateway:${CIRCLE_SHA1}"
          paths:
            - docker-cache
      - persist_to_workspace: 
          root: ./
          paths: 
              - ./package.json

  unit-test:
    <<: *defaults
    steps:
      - restore_cache:
          key: "clark-gateway:${CIRCLE_SHA1}"
      - setup_remote_docker
      - run:
          name: Unit Test Image
          command: |
            docker load < docker-cache/built-image.tar
            echo docker run-it -d clark-gateway:$CIRCLE_SHA1 npm test
      - run:
          name: Login to docker
          command: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run:
          name: Publish Image 
          command: |
            docker tag clark-gateway:$CIRCLE_SHA1 "${DOCKER_USER_ORG}/clark-gateway:${CIRCLE_SHA1}"
            docker push "${DOCKER_USER_ORG}/clark-gateway:${CIRCLE_SHA1}"

  integration-test:
    <<: *defaults
    docker:
      - image: docker:17.05.0-ce-git
      - image: node:8-alpine
    steps:
      - attach_workspace : 
          at: *working_directory
      - setup_remote_docker
      - run:
          name: Pull Image
          command: docker pull "${DOCKER_USER_ORG}/clark-gateway:${CIRCLE_SHA1}"
      - run:
          name: Run Integration Test
          command: |
            docker build -t clark-gateway:${CIRCLE_SHA1}
            echo docker run-it -d clark-gateway:$CIRCLE_SHA1 npm test
      - run:
          name: Login to docker
          command: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run:
          name: Publish Image 
          command: |
            docker tag clark-gateway:$(node -p "require('./package.json').version") "${DOCKER_USER_ORG}/clark-gateway:${(node -p "require('./package.json').version")}"
            docker push "${DOCKER_USER_ORG}/clark-gateway:${(node -p "require('./package.json').version")}"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - integration-test:
          requires:
            - unit-test

  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /master/
      - unit-test:
          requires:
            - build
          filters:
            branches:
              only: /master/
      - integration-test:
          requires:
            - unit-test
          filters:
            branches:
              only: /master/
      - deploy:
          requires:
            - integration-test
          filters:
            branches:
              only: /master/