version: 2.1
orbs:
    cyber4all: cyber4all/orb@2.1.8
    docker: circleci/docker@2.2.0

workflows:
    integration-testing:
        jobs:
            - cyber4all/publish:
                  image: "cyber4all/clark-gateway"
                  deploy: false

            - cyber4all/lint

            - docker/hadolint:
                  ignore-rules: "DL3018,DL3019"

    deploy-clark-service-refactor:
        when:
            equal: [clark-service-refactor, <<pipeline.git.branch>>]
        jobs:
            - cyber4all/publish:
                  context: [DockerHub]
                  image: "cyber4all/clark-gateway"
                  tag: "staging"

    deploy-production:
        when:
            equal: [releases, <<pipeline.git.branch>>]
        jobs:
            - cyber4all/publish:
                  context: [DockerHub]
                  image: "cyber4all/clark-gateway"
                  tag: "$(jq -r '.version' package.json),latest"

            # TODO: Add a job to deploy the new version to ECS
            # once we have the ECS infrastructure in place
            # for the CLARD environment
