defaults: &defaults
  working_directory: ~/CLARK-Gateway
  docker:
    - image: cyber4all/circleci-aws:node-alpine
orbs:
  aws-cli: circleci/aws-cli@1.2.1
commands:
  install-aws: aws-cli/install
  setup-aws-cli: aws-cli/setup
version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run build
      - persist_to_workspace: 
          root: ./
          paths: 
              - ./dist
              - ./package.json
              - ./package-lock.json
              - ./.elasticbeanstalk
              - ./docs
              - ./Procfile
  deploy:
    <<: *defaults
    steps:
      - attach_workspace : 
          at: ~/CLARK-Gateway
      - setup-aws-cli:
          aws-access-key-id: AWS_EB_AccessKey
          aws-region: AWS_REGION_N_VA
          aws-secret-access-key: AWS_EB_SecretKey
          version: "1"
      - run:
          name: Install prod dependencies
          command: npm install --only=prod
      - run:
          name: Setup AWS credentials
          command: |
            mkdir ~/.aws && printf "[profile default]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/config
      - run: 
          name: Zip dist
          command: zip -r dist.zip . *
      - run:
          name: Deploy to Elastic Beanstalk 
          command: eb deploy Gateway-API --verbose --label Gateway-API-v$(node -p "require('./package.json').version")
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /master/
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /master/
      - deploy:
          requires:
            - build
          context:
            - AWS
          filters:
            branches:
              only: /master/