defaults: &defaults
  working_directory: ~/CLARK-Gateway
  docker:
    - image: circleci/node:8.10.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: 'dependency-cache-{{ checksum "package.json" }}'
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: 'dependency-cache-{{ checksum "package.json" }}'
          paths:
            - ~/.cache/npm
            - ./node_modules
      - run:
          name: Build Application
          command: npm run build
      - persist_to_workspace: 
          root: ./
          paths: 
              - ./dist
              - ./package.json
              - ./.elasticbeanstalk
  test:
    <<: *defaults
    steps:
      - attach_workspace : 
          at: ~/CLARK-Gateway
      - run: echo 'We need tests'
      - run:
          name: Check Directory
          command: ls
  deploy:
    <<: *defaults
    docker:
      - image: 'wilson208/circleci-awscli'
    steps:
      - attach_workspace : 
          at: ~/CLARK-Gateway
      - run: 
          name: Zip Package for Deployment
          command: npm run zip
      - run:
          name: Deploy to Elastic Beanstalk 
          command: npm run deploy
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
