defaults: &defaults
  working_directory: ~/CLARK-Gateway
  docker:
    - image: mesosphere/aws-cli:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build Image
          command: docker build -t clark-gateway:$CIRCLE_SHA1