defaults: &defaults
  working_directory: ~/CLARK-Gateway
  docker:
    - image: docker:17.05.0-ce-git
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: | 
            docker build -t clark-gateway:$CIRCLE_SHA1 .
            mkdir -p docker-cache
            docker save -o docker-cache/built-image.tar clark-gateway:$CIRCLE_SHA1
      - save_cache:
          key: clark-gateway-build
          paths:
            - docker-cache

  test:
    <<: *defaults
    docker:
      - image: mesosphere/aws-cli:latest
    steps:
      - restore_cache:
          key: clark-gateway-build
      - setup_remote_docker
      - run:
          name: Unit Test Image
          command: |
            docker load < docker-cache/built-image.tar
            echo We need tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /master/
      - test:
          requires:
            - build
          filters:
            branches:
              only: /master/
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: /master/