defaults: &defaults
  working_directory: ~/CLARK-Gateway
  docker:
    - image: cyber4all/circleci-aws:node-alpine

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run build
      - persist_to_workspace: 
          root: ./
          paths: 
              - ./dist
              - ./package.json
              - ./package-lock.json
              - ./.elasticbeanstalk
              - ./docs
              - ./Procfile
  deploy:
    <<: *defaults
    steps:
      - attach_workspace : 
          at: ~/CLARK-Gateway
      - run:
          name: Install prod dependencies
          command: npm install --only=prod
      - run:
          name: Setup AWS credentials
          command: |
            mkdir ~/.aws && printf "[profile default]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/config
      - run: 
          name: Zip dist
          command: zip -r dist.zip . *
      - run:
          name: Show Content
          command: ls
      # - run:
      #     name: Deploy to Elastic Beanstalk 
      #     command: eb deploy Gateway-API --verbose --label Gateway-API-v$(node -p "require('./package.json').version")
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /master/
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /master/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /master/